# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-cd1d19c8-dc8e-490c-b279-6a699e0aa738";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cd1d19c8-dc8e-490c-b279-6a699e0aa738".device = "/dev/disk/by-uuid/cd1d19c8-dc8e-490c-b279-6a699e0aa738";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8AEA-1992";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3342c12e-259e-45d5-8592-dbba43ae755e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
